version: 2
jobs:
  build:
    working_directory: ~/AMIRY_API
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      - image: circleci/mysql:5.7
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: ''

    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Database creation
          command: |
            bundle exec rake db:create RAILS_ENV=test
            bundle exec rake db:schema:load RAILS_ENV=test
            bundle exec rake db:migrate RAILS_ENV=test
      - run:
          name: Inserting Seed Data
          command: |
            bundle exec rake db:seed:university RAILS_ENV=test
            bundle exec rake db:seed:user RAILS_ENV=test
            bundle exec rake db:seed:like RAILS_ENV=test
            bundle exec rake db:seed:matching RAILS_ENV=test
            bundle exec rake db:seed:introduction RAILS_ENV=test
      - run:
          name: rspec
          command: bundle exec rspec
      - run:
          name: rubocop
          command: bundle exec rubocop
